version: '3'
services:
  app:
    container_name: app
    image: app
    build:
      context: . 
      dockerfile: Dockerfile
    networks:
      - backend

  proxy-nginx:
    container_name: proxy-nginx
    image: proxy-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - app

networks:
  backend:
    driver: bridge
