version: '3'
services:
  app2:
    container_name: app
    image: app
    build:
      context: . 
      dockerfile: Dockerfile
    networks:
      - backend
  proxy:
    container_name: proxy-nginx
    image: proxy-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - app2

networks:
  backend:
    driver: bridge
