version: '3'
services:
  app2:
    container_name: app
    image: app
    build:
      context: . 
      dockerfile: Dockerfile
  proxy:
    container_name: proxy-nginx
    image: proxy-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app2
